version: '3.5'

services:
  spa:
    build: ./
    ports:
      - 5000:5000
    environment:
      PRODUCTION: 'true'
      SECRET_KEY: 'secretKey123'
      UPLOAD_FOLDER: '/server/uploads'
      DATABASE_URI: 'sqlite:////server/test.db'





  postgres:
    image: 'postgres'
    ports:
      - 8001:8001
    environment:
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_USER: 'postgres'
